version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fullstack-gestao-de-ensino-labpcp
    ports:
      - "5435:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: labpcp
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: